cmake_minimum_required(VERSION 3.14)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/out)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/out)
project(ProjectRoot LANGUAGES CXX)
set(PROJECTROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}" CACHE INTERNAL "Project root dir")
add_subdirectory(searchcore_dir)