services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: search-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./search.py:/app/search.py
      - ./docs:/app/docs
    environment:
      PYTHONPATH: /app:/app/build:/app/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: search-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

